### ISSUE TITLE
Using the backbone wp-api client

### ISSUE THREAD

**Issue by JulienMelissas** [JulienMelissas/wp-api-guides#4]
I think it would be awesome if @adamsilverstein maybe wanted to take this one on? 😉

**Comment by adamsilverstein** [comment]
@JulienMelissas I do have this guide started as part of the handbook rest-api documentation @ https://developer.wordpress.org/rest-api/using-the-rest-api/backbone-javascript-client/, although I know it needs some work. Do you think this is the right format, or are you thinking about something more general that outlines the functionality/uses without diving into technical details?

**Comment by JulienMelissas** [comment]
@adamsilverstein thanks for the reply!! I think that guide is really great and would totally work. Maybe we can just link to it? I'm going to be merging in Zac's updates and we'll see if the formatting fits then...

**Comment by JulienMelissas** [comment]
(closing for now)
